/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    reservations: Reservation;
    customers: Customer;
    handovers: Handover;
    penalties: Penalty;
    'corporate-requests': CorporateRequest;
    'vehicle-models': VehicleModel;
    vehicles: Vehicle;
    'vehicle-blocks': VehicleBlock;
    'vehicle-categories': VehicleCategory;
    locations: Location;
    seasons: Season;
    extras: Extra;
    'transfer-fees': TransferFee;
    pages: Page;
    faqs: Faq;
    media: Media;
    documents: Document;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    reservations: {
      handovers: 'handovers';
      penalties: 'penalties';
    };
    customers: {
      reservations: 'reservations';
    };
  };
  collectionsSelect: {
    reservations: ReservationsSelect<false> | ReservationsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    handovers: HandoversSelect<false> | HandoversSelect<true>;
    penalties: PenaltiesSelect<false> | PenaltiesSelect<true>;
    'corporate-requests': CorporateRequestsSelect<false> | CorporateRequestsSelect<true>;
    'vehicle-models': VehicleModelsSelect<false> | VehicleModelsSelect<true>;
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    'vehicle-blocks': VehicleBlocksSelect<false> | VehicleBlocksSelect<true>;
    'vehicle-categories': VehicleCategoriesSelect<false> | VehicleCategoriesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    seasons: SeasonsSelect<false> | SeasonsSelect<true>;
    extras: ExtrasSelect<false> | ExtrasSelect<true>;
    'transfer-fees': TransferFeesSelect<false> | TransferFeesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    ('false' | 'none' | 'null') | false | null | ('tr' | 'en' | 'de' | 'ru') | ('tr' | 'en' | 'de' | 'ru')[];
  globals: {
    settings: Setting;
    'exchange-rates': ExchangeRate;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'exchange-rates': ExchangeRatesSelect<false> | ExchangeRatesSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: 'tr' | 'en' | 'de' | 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      refreshExchangeRates: TaskRefreshExchangeRates;
      sendReservationNotification: TaskSendReservationNotification;
      sendCorporateRequestNotification: TaskSendCorporateRequestNotification;
      sendPickupReminders: TaskSendPickupReminders;
      sendVehicleDocumentReminders: TaskSendVehicleDocumentReminders;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: number;
  code?: string | null;
  status: 'pending' | 'confirmed' | 'active' | 'completed' | 'cancelled' | 'no_show';
  /**
   * Calculated from payments; set "Refunded" manually.
   */
  paymentStatus: 'unpaid' | 'partial' | 'paid' | 'refunded';
  source: 'web' | 'mobile' | 'phone' | 'walk_in' | 'corporate';
  locale?: string | null;
  customer: number | Customer;
  vehicleModel: number | VehicleModel;
  /**
   * Assign a plate when confirming. A different model means an upgrade.
   */
  vehicle?: (number | null) | Vehicle;
  pickupLocation: number | Location;
  returnLocation: number | Location;
  pickupAt: string;
  returnAt: string;
  flightNumber?: string | null;
  preferredPaymentMethod: 'office' | 'bank_transfer';
  additionalDrivers?:
    | {
        fullName: string;
        licenseNumber?: string | null;
        birthDate?: string | null;
        id?: string | null;
      }[]
    | null;
  customerNote?: string | null;
  internalNote?: string | null;
  extras?:
    | {
        extra: number | Extra;
        quantity: number;
        name?: string | null;
        unitPrice?: number | null;
        chargedDays?: number | null;
        total?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Prices are frozen at booking time. Tick this after changing dates, model, locations or extras.
   */
  recalculatePrice?: boolean | null;
  pricing?: {
    currency?: ('EUR' | 'TRY' | 'USD' | 'GBP') | null;
    rentalDays?: number | null;
    baseTotal?: number | null;
    extrasTotal?: number | null;
    transferFee?: number | null;
    discount?: number | null;
    total?: number | null;
    deposit?: number | null;
    dailyBreakdown?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Currency the customer browsed in, with the rate at booking time. For information only.
   */
  display?: {
    currency?: ('EUR' | 'TRY' | 'USD' | 'GBP') | null;
    rate?: number | null;
    total?: number | null;
  };
  payments?:
    | {
        amount: number;
        method: 'office_cash' | 'office_card' | 'bank_transfer';
        paidAt: string;
        reference?: string | null;
        proof?: (number | null) | Document;
        id?: string | null;
      }[]
    | null;
  paidTotal?: number | null;
  confirmedAt?: string | null;
  cancelledAt?: string | null;
  cancelReason?: string | null;
  reminderSentAt?: string | null;
  handovers?: {
    docs?: (number | Handover)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  penalties?: {
    docs?: (number | Penalty)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  fullName?: string | null;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  country?: string | null;
  birthDate?: string | null;
  preferredLocale?: string | null;
  idDocumentType?: ('national_id' | 'passport') | null;
  idDocumentNumber?: string | null;
  licenseNumber?: string | null;
  licenseCountry?: string | null;
  licenseIssuedAt?: string | null;
  address?: string | null;
  privacyAcceptedAt?: string | null;
  marketingConsent?: boolean | null;
  marketingConsentAt?: string | null;
  isBlacklisted?: boolean | null;
  blacklistReason?: string | null;
  notes?: string | null;
  reservations?: {
    docs?: (number | Reservation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-models".
 */
export interface VehicleModel {
  id: number;
  /**
   * Brand + model.
   */
  name?: string | null;
  /**
   * Generated automatically when left empty.
   */
  slug?: string | null;
  isActive?: boolean | null;
  isFeatured?: boolean | null;
  sortOrder?: number | null;
  brand: string;
  model: string;
  category: number | VehicleCategory;
  /**
   * The first image is the cover.
   */
  images?: (number | Media)[] | null;
  description?: string | null;
  transmission: 'manual' | 'automatic';
  fuelType: 'petrol' | 'diesel' | 'hybrid' | 'electric' | 'lpg';
  seats: number;
  doors: number;
  largeBags: number;
  smallBags: number;
  features?:
    | (
        | 'air_conditioning'
        | 'bluetooth'
        | 'navigation'
        | 'cruise_control'
        | 'parking_sensors'
        | 'rear_camera'
        | 'apple_carplay'
        | 'android_auto'
        | 'sunroof'
        | 'heated_seats'
        | 'usb'
        | 'isofix'
      )[]
    | null;
  minDriverAge: number;
  minLicenseYears: number;
  /**
   * Empty = unlimited.
   */
  dailyKmLimit?: number | null;
  extraKmFee?: number | null;
  deposit: number;
  /**
   * The tier with the highest "from days" not exceeding the rental length applies to every day. A tier starting at 1 day is required. Seasons adjust these rates.
   */
  rateTiers: {
    minDays: number;
    dailyRate: number;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-categories".
 */
export interface VehicleCategory {
  id: number;
  name: string;
  /**
   * Generated automatically when left empty.
   */
  slug?: string | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Shown under the photo, e.g. “Jane Doe / Wikimedia Commons, CC BY-SA 4.0”.
   */
  credit?: string | null;
  creditUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: number;
  plate: string;
  vehicleModel: number | VehicleModel;
  /**
   * Updated automatically on return.
   */
  location: number | Location;
  status: 'active' | 'maintenance' | 'inactive' | 'sold';
  year?: number | null;
  color?: string | null;
  vin?: string | null;
  mileageKm?: number | null;
  insuranceExpiresAt?: string | null;
  cascoExpiresAt?: string | null;
  inspectionExpiresAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  /**
   * Generated automatically when left empty.
   */
  slug?: string | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  allowsPickup?: boolean | null;
  allowsReturn?: boolean | null;
  address: string;
  city: string;
  country?: string | null;
  phone: string;
  whatsapp?: string | null;
  email?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  timeZone: string;
  /**
   * One row per weekday. Missing days are treated as closed.
   */
  openingHours?:
    | {
        day: 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';
        opensAt: string;
        closesAt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "extras".
 */
export interface Extra {
  id: number;
  name: string;
  /**
   * Generated automatically when left empty.
   */
  slug?: string | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  description?: string | null;
  pricingType: 'per_day' | 'per_rental';
  price: number;
  maxQuantity: number;
  /**
   * Empty = every day is charged.
   */
  maxChargeDays?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "handovers".
 */
export interface Handover {
  id: number;
  reservation: number | Reservation;
  type: 'pickup' | 'return';
  performedAt: string;
  mileageKm: number;
  fuelLevel: 'empty' | 'quarter' | 'half' | 'three_quarters' | 'full';
  damages?:
    | {
        area: 'front' | 'rear' | 'left' | 'right' | 'roof' | 'interior' | 'windshield' | 'wheels' | 'other';
        description: string;
        isNew?: boolean | null;
        photo?: (number | null) | Document;
        id?: string | null;
      }[]
    | null;
  photos?: (number | Document)[] | null;
  notes?: string | null;
  performedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'staff';
  /**
   * Staff only see reservations of these locations.
   */
  locations?: (number | Location)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "penalties".
 */
export interface Penalty {
  id: number;
  type: 'toll' | 'traffic_fine' | 'damage' | 'fuel' | 'extra_km' | 'late_return' | 'other';
  status: 'open' | 'charged' | 'paid' | 'waived';
  vehicle: number | Vehicle;
  /**
   * The rental during which it occurred.
   */
  reservation?: (number | null) | Reservation;
  amount: number;
  occurredAt: string;
  document?: (number | null) | Document;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corporate-requests".
 */
export interface CorporateRequest {
  id: number;
  status: 'new' | 'contacted' | 'quoted' | 'won' | 'lost';
  locale?: string | null;
  companyName: string;
  taxNumber?: string | null;
  contactName: string;
  email: string;
  phone: string;
  country?: string | null;
  vehicleCount: number;
  startDate: string;
  durationMonths: number;
  vehicleCategories?: (number | VehicleCategory)[] | null;
  notes?: string | null;
  privacyAcceptedAt?: string | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Block a vehicle for maintenance or repair so it cannot be booked.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-blocks".
 */
export interface VehicleBlock {
  id: number;
  vehicle: number | Vehicle;
  reason: 'maintenance' | 'repair' | 'inspection' | 'other';
  startsAt: string;
  endsAt: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * When seasons overlap, the one with the highest priority wins for that day.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons".
 */
export interface Season {
  id: number;
  name: string;
  isActive?: boolean | null;
  startDate: string;
  endDate: string;
  /**
   * e.g. 30 = +30%, -15 = -15%
   */
  adjustmentPercent: number;
  priority: number;
  minRentalDays?: number | null;
  /**
   * Empty = all categories.
   */
  vehicleCategories?: (number | VehicleCategory)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfer-fees".
 */
export interface TransferFee {
  id: number;
  fromLocation: number | Location;
  toLocation: number | Location;
  fee: number;
  bidirectional?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Generated automatically when left empty.
   */
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'booking' | 'payment' | 'requirements' | 'insurance' | 'other';
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'refreshExchangeRates'
          | 'sendReservationNotification'
          | 'sendCorporateRequestNotification'
          | 'sendPickupReminders'
          | 'sendVehicleDocumentReminders';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'refreshExchangeRates'
        | 'sendReservationNotification'
        | 'sendCorporateRequestNotification'
        | 'sendPickupReminders'
        | 'sendVehicleDocumentReminders'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'reservations';
        value: number | Reservation;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'handovers';
        value: number | Handover;
      } | null)
    | ({
        relationTo: 'penalties';
        value: number | Penalty;
      } | null)
    | ({
        relationTo: 'corporate-requests';
        value: number | CorporateRequest;
      } | null)
    | ({
        relationTo: 'vehicle-models';
        value: number | VehicleModel;
      } | null)
    | ({
        relationTo: 'vehicles';
        value: number | Vehicle;
      } | null)
    | ({
        relationTo: 'vehicle-blocks';
        value: number | VehicleBlock;
      } | null)
    | ({
        relationTo: 'vehicle-categories';
        value: number | VehicleCategory;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'seasons';
        value: number | Season;
      } | null)
    | ({
        relationTo: 'extras';
        value: number | Extra;
      } | null)
    | ({
        relationTo: 'transfer-fees';
        value: number | TransferFee;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  code?: T;
  status?: T;
  paymentStatus?: T;
  source?: T;
  locale?: T;
  customer?: T;
  vehicleModel?: T;
  vehicle?: T;
  pickupLocation?: T;
  returnLocation?: T;
  pickupAt?: T;
  returnAt?: T;
  flightNumber?: T;
  preferredPaymentMethod?: T;
  additionalDrivers?:
    | T
    | {
        fullName?: T;
        licenseNumber?: T;
        birthDate?: T;
        id?: T;
      };
  customerNote?: T;
  internalNote?: T;
  extras?:
    | T
    | {
        extra?: T;
        quantity?: T;
        name?: T;
        unitPrice?: T;
        chargedDays?: T;
        total?: T;
        id?: T;
      };
  recalculatePrice?: T;
  pricing?:
    | T
    | {
        currency?: T;
        rentalDays?: T;
        baseTotal?: T;
        extrasTotal?: T;
        transferFee?: T;
        discount?: T;
        total?: T;
        deposit?: T;
        dailyBreakdown?: T;
      };
  display?:
    | T
    | {
        currency?: T;
        rate?: T;
        total?: T;
      };
  payments?:
    | T
    | {
        amount?: T;
        method?: T;
        paidAt?: T;
        reference?: T;
        proof?: T;
        id?: T;
      };
  paidTotal?: T;
  confirmedAt?: T;
  cancelledAt?: T;
  cancelReason?: T;
  reminderSentAt?: T;
  handovers?: T;
  penalties?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  fullName?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  country?: T;
  birthDate?: T;
  preferredLocale?: T;
  idDocumentType?: T;
  idDocumentNumber?: T;
  licenseNumber?: T;
  licenseCountry?: T;
  licenseIssuedAt?: T;
  address?: T;
  privacyAcceptedAt?: T;
  marketingConsent?: T;
  marketingConsentAt?: T;
  isBlacklisted?: T;
  blacklistReason?: T;
  notes?: T;
  reservations?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "handovers_select".
 */
export interface HandoversSelect<T extends boolean = true> {
  reservation?: T;
  type?: T;
  performedAt?: T;
  mileageKm?: T;
  fuelLevel?: T;
  damages?:
    | T
    | {
        area?: T;
        description?: T;
        isNew?: T;
        photo?: T;
        id?: T;
      };
  photos?: T;
  notes?: T;
  performedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "penalties_select".
 */
export interface PenaltiesSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  vehicle?: T;
  reservation?: T;
  amount?: T;
  occurredAt?: T;
  document?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corporate-requests_select".
 */
export interface CorporateRequestsSelect<T extends boolean = true> {
  status?: T;
  locale?: T;
  companyName?: T;
  taxNumber?: T;
  contactName?: T;
  email?: T;
  phone?: T;
  country?: T;
  vehicleCount?: T;
  startDate?: T;
  durationMonths?: T;
  vehicleCategories?: T;
  notes?: T;
  privacyAcceptedAt?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-models_select".
 */
export interface VehicleModelsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isActive?: T;
  isFeatured?: T;
  sortOrder?: T;
  brand?: T;
  model?: T;
  category?: T;
  images?: T;
  description?: T;
  transmission?: T;
  fuelType?: T;
  seats?: T;
  doors?: T;
  largeBags?: T;
  smallBags?: T;
  features?: T;
  minDriverAge?: T;
  minLicenseYears?: T;
  dailyKmLimit?: T;
  extraKmFee?: T;
  deposit?: T;
  rateTiers?:
    | T
    | {
        minDays?: T;
        dailyRate?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  plate?: T;
  vehicleModel?: T;
  location?: T;
  status?: T;
  year?: T;
  color?: T;
  vin?: T;
  mileageKm?: T;
  insuranceExpiresAt?: T;
  cascoExpiresAt?: T;
  inspectionExpiresAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-blocks_select".
 */
export interface VehicleBlocksSelect<T extends boolean = true> {
  vehicle?: T;
  reason?: T;
  startsAt?: T;
  endsAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-categories_select".
 */
export interface VehicleCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isActive?: T;
  sortOrder?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isActive?: T;
  sortOrder?: T;
  allowsPickup?: T;
  allowsReturn?: T;
  address?: T;
  city?: T;
  country?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  latitude?: T;
  longitude?: T;
  timeZone?: T;
  openingHours?:
    | T
    | {
        day?: T;
        opensAt?: T;
        closesAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons_select".
 */
export interface SeasonsSelect<T extends boolean = true> {
  name?: T;
  isActive?: T;
  startDate?: T;
  endDate?: T;
  adjustmentPercent?: T;
  priority?: T;
  minRentalDays?: T;
  vehicleCategories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "extras_select".
 */
export interface ExtrasSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isActive?: T;
  sortOrder?: T;
  description?: T;
  pricingType?: T;
  price?: T;
  maxQuantity?: T;
  maxChargeDays?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfer-fees_select".
 */
export interface TransferFeesSelect<T extends boolean = true> {
  fromLocation?: T;
  toLocation?: T;
  fee?: T;
  bidirectional?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  creditUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  locations?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  companyName: string;
  legalName?: string | null;
  /**
   * Shown on the website as the rental regulation requires.
   */
  authorizationNumber?: string | null;
  taxOffice?: string | null;
  taxNumber?: string | null;
  mersisNumber?: string | null;
  phone?: string | null;
  /**
   * International format, e.g. 905551112233
   */
  whatsapp?: string | null;
  email?: string | null;
  address?: string | null;
  socialLinks?: {
    instagram?: string | null;
    facebook?: string | null;
    x?: string | null;
    youtube?: string | null;
  };
  /**
   * All prices in the panel are entered in this currency. Changing it later does not convert existing prices.
   */
  baseCurrency: 'EUR' | 'TRY' | 'USD' | 'GBP';
  displayCurrencies?: ('EUR' | 'TRY' | 'USD' | 'GBP')[] | null;
  bankAccounts?:
    | {
        bankName: string;
        accountHolder: string;
        iban: string;
        currency: 'EUR' | 'TRY' | 'USD' | 'GBP';
        id?: string | null;
      }[]
    | null;
  reservationRules: {
    minLeadTimeHours: number;
    minRentalDays: number;
    /**
     * Longer rentals go through the corporate form.
     */
    maxRentalDays: number;
    maxAdvanceDays: number;
    graceMinutes: number;
    bufferMinutes: number;
    selfCancelCutoffHours: number;
  };
  cancellationPolicy?: string | null;
  notificationEmails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 1 unit of the base currency = rate × target currency. Updated daily from the Central Bank (TCMB).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exchange-rates".
 */
export interface ExchangeRate {
  id: number;
  baseCurrency?: ('EUR' | 'TRY' | 'USD' | 'GBP') | null;
  rates?:
    | {
        currency: 'EUR' | 'TRY' | 'USD' | 'GBP';
        rate: number;
        id?: string | null;
      }[]
    | null;
  source?: string | null;
  fetchedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  companyName?: T;
  legalName?: T;
  authorizationNumber?: T;
  taxOffice?: T;
  taxNumber?: T;
  mersisNumber?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  address?: T;
  socialLinks?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        x?: T;
        youtube?: T;
      };
  baseCurrency?: T;
  displayCurrencies?: T;
  bankAccounts?:
    | T
    | {
        bankName?: T;
        accountHolder?: T;
        iban?: T;
        currency?: T;
        id?: T;
      };
  reservationRules?:
    | T
    | {
        minLeadTimeHours?: T;
        minRentalDays?: T;
        maxRentalDays?: T;
        maxAdvanceDays?: T;
        graceMinutes?: T;
        bufferMinutes?: T;
        selfCancelCutoffHours?: T;
      };
  cancellationPolicy?: T;
  notificationEmails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exchange-rates_select".
 */
export interface ExchangeRatesSelect<T extends boolean = true> {
  baseCurrency?: T;
  rates?:
    | T
    | {
        currency?: T;
        rate?: T;
        id?: T;
      };
  source?: T;
  fetchedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRefreshExchangeRates".
 */
export interface TaskRefreshExchangeRates {
  input?: unknown;
  output: {
    status: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendReservationNotification".
 */
export interface TaskSendReservationNotification {
  input: {
    reservationId: number;
    audience: 'customer' | 'staff';
    event: 'created' | 'confirmed' | 'cancelled' | 'reminder';
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendCorporateRequestNotification".
 */
export interface TaskSendCorporateRequestNotification {
  input: {
    corporateRequestId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendPickupReminders".
 */
export interface TaskSendPickupReminders {
  input?: unknown;
  output: {
    sent: number;
    failed: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendVehicleDocumentReminders".
 */
export interface TaskSendVehicleDocumentReminders {
  input?: unknown;
  output: {
    items: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}